openapi: 3.0.0
info:
  title: Event Delivery API
  version: 1.0.0
servers:
  - url: https://{BaseUrl}
paths:
  /event/entity/{entityId}:
    get:
      summary: Get event ids for an entity
      parameters:
        - name: entityId
          in: path
          required: true
          description: The unique identifier for the entity
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - entityId
                  - eventIds
                properties:
                  entityId:
                    type: string
                    description: The unique identifier for the entity
                  eventIds:
                    type: array
                    items:
                      type: string
                    description: Array of event ids for the entity in sequential order
                example:
                  entityId: "9051760d-8dfa-4352-9275-d75758828c39"
                  eventIds: ["dfe28b6f-9259-48a4-8772-c9329fb7bbcc","b662f105-1d85-465b-b2f1-d5e03904e926"]
        "404":
          description: Not Found
        
  /event/{eventId}:
    get:
      summary: Get event details
      description: Retrieves the details of a specific event.
      parameters:
        - name: eventId
          in: path
          required: true
          description: The unique identifier for the event.
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - eventId
                  - eventType
                  - payload
                  - entityId
                  - entitySequenceNumber
                properties:
                  eventId:
                    type: string
                    description: The unique identifier for the event.
                  eventType:
                    type: string
                    description: The type of the event.
                    enum:
                      - projectCreated
                      - jobAssigned
                      - projectDetailUpdated
                      - jobDetailUpdated
                  payload:
                    oneOf:
                      - $ref: "#/components/schemas/ProjectCreated"
                      - $ref: "#/components/schemas/JobAssigned"
                      - $ref: "#/components/schemas/ProjectDetailUpdated"
                      - $ref: "#/components/schemas/JobDetailUpdated"
                  entityId:
                    type: string
                    description: The unique identifier for the entity associated with the event.
                  entitySequenceNumber:
                    type: integer
                    description: The sequence number of the event for the associated entity.
              examples:
                projectCreated:
                  value:
                    eventId: "dfe28b6f-9259-48a4-8772-c9329fb7bbcc"
                    eventType: "projectCreated"
                    entityId: "9051760d-8dfa-4352-9275-d75758828c39"
                    entitySequenceNumber: 1
                    payload:
                      projectId: "9051760d-8dfa-4352-9275-d75758828c39"
                      claimReference: "C5678"
                      supplierId: "V9012"
                      eventDetails:
                        eventType: "flood"
                        eventDesc: "Flood damage to basement"
                        eventDateTime: "2022-04-15T10:30:00Z"
                        catCode: "Flood"
                      excess:
                        buildingExcess: 2000
                        contentsExcess: 1000
                        fixedExcess: 2500
                      siteAddress:
                        streetNumber: "123"
                        streetName: "Main St"
                        suburb: "Central"
                        city: "Sydney"
                        state: "NSW"
                        postCode: "2000"
                        country: "Australia"
                      postalAddress:
                        streetNumber: "PO Box 1234"
                        suburb: "Central"
                        city: "Sydney"
                        state: "NSW"
                        postCode: "2000"
                        country: "Australia"
                      insuredDetails:
                        firstName: "John"
                        lastName: "Doe"
                        homeNumber: "02 1234 5678"
                        mobileNumber: "0412 345 678"
                        email: "johndoe@example.com"
                        companyName: "ABC Pty Ltd"
                      projectStatus: "open"
                jobAssigned:
                  value:
                    eventId: "44c2a980-8254-43d6-9a95-98c886f4cd78"
                    eventType: "jobAssigned"
                    entityId: "eb54d5e7-7f15-4b13-b8c9-623d2aac98c3"
                    entitySequenceNumber: 1
                    payload:
                      projectId: "9051760d-8dfa-4352-9275-d75758828c39"
                      jobId: "eb54d5e7-7f15-4b13-b8c9-623d2aac98c3"
                      jobType: "assessAndRepair"
                      jobInstructions: "Please assess the damage and repair as necessary."
                      supplierId: "V9012"
                      jobStatus: "accepted"
                      jobReference: "ref123"
                projectDetailUpdated:
                  value:
                    eventId: "b662f105-1d85-465b-b2f1-d5e03904e926"
                    eventType: "projectDetailUpdated"
                    entityId: "9051760d-8dfa-4352-9275-d75758828c39"
                    entitySequenceNumber: 2
                    payload:
                      projectId: "9051760d-8dfa-4352-9275-d75758828c39"
                      excess:
                        buildingExcess: 2000
                        contentsExcess: 1000
                        fixedExcess: 2500
                      siteAddress:
                        unitNumber: "1A"
                        streetNumber: "123"
                        streetName: "Main St"
                        suburb: "Exampleville"
                        city: "Example City"
                        state: "EX"
                        postCode: "1234"
                        country: "Exampleland"
                      insuredDetails:
                        firstName: "John"
                        lastName: "Doe"
                        homeNumber: "1234567890"
                        mobileNumber: "0987654321"
                        email: "johndoe@example.com"
                        companyName: "Example Inc."
                      eventDetails:
                        catCode: "CAT-123"
                      projectStatus: "open"
                jobDetailUpdated:
                  value:
                    eventId: "8e2cad32-c7fa-4839-9422-76b85ae778ac"
                    eventType: "jobDetailUpdated"
                    entityId: "eb54d5e7-7f15-4b13-b8c9-623d2aac98c3"
                    entitySequenceNumber: 2
                    payload:
                      jobId: "eb54d5e7-7f15-4b13-b8c9-623d2aac98c3"
                      jobStatus: "awaitingA&GReview"
        "404":
          description: Not Found
components:
  schemas:
    ProjectCreated:
      type: object
      required:
        - projectId
        - claimReference
        - supplierId
        - eventDetails
        - excess
        - siteAddress
        - postalAddress
        - insuredDetails
      properties:
        projectId:
          type: string
          description: The ID of the project associated with the claim.
        claimReference:
          type: string
          description: The reference code for the claim.
        supplierId:
          type: string
          description: The ID of the vendor associated with the claim.
        eventDetails:
          type: object
          required:
            - eventType
            - eventDesc
            - eventDateTime
          properties:
            eventType:
              type: string
              enum:
                - accidentalDamageLoss
                - bushfire
                - tenantDefault
                - escapeOfLiquid
                - earthMovement
                - earthquake
                - explosion
                - fireDamage
                - flood
                - glass
                - hail
                - impact
                - lightning
                - motorBurnout
                - maliciousDamageVandalism
                - thirdPartyPersonalInjury
                - personalEffects
                - riotCivilCommotion
                - rainwaterRunoff
                - stormWind
                - theftDamage
                - theft
                - liabilityThirdParty
                - tenantMaliciousDamage
                - thirdPartyProperty
                - tenantTheft
              description: The type of the event.
            eventDesc:
              type: string
              description: The description of the event.
            eventDateTime:
              type: string
              format: date-time
              description: The date and time of the event.
            catCode:
              type: string
              description: The catastrophe code of the event.
          description: The details of the event that caused the claim.
        excess:
          type: object
          required:
            - buildingExcess
            - contentsExcess
          properties:
            buildingExcess:
              type: integer
              description: The excess amount for a building claim.
            contentsExcess:
              type: integer
              description: The excess amount for a contents claim.
            fixedExcess:
              type: integer
              description: The fixed excess amount for the claim.
            totalExcess:
              type: integer
              description: The total excess amount for the claim.
          description: The excess amount for the claim.
        siteAddress:
          allOf:
            - $ref: "#/components/schemas/Address"
            - description: The site address for the claim.
        postalAddress:
          allOf:
            - description: The postal address for the claim.
            - $ref: "#/components/schemas/Address"
        insuredDetails:
          type: object
          required:
            - firstName
            - lastName
            - homeNumber
            - mobileNumber
            - email
            - companyName
          properties:
            firstName:
              type: string
              description: The first name of the insured person or company.
            lastName:
              type: string
              description: The last name of the insured person or company.
            homeNumber:
              type: string
              description: The home phone number of the insured person or company.
            mobileNumber:
              type: string
              description: The mobile phone number of the insured person or company.
            email:
              type: string
              format: email
              description: The email address of the insured person or company.
            companyName:
              type: string
              description: The name of the insured company, if applicable.
          description: The details of the insured person or company.
        projectStatus:
          type: string
          enum:
            - open
            - closed
          description: The project Status
    JobAssigned:
      type: object
      required:
        - projectId
        - jobId
        - jobType
        - jobInstructions
        - supplierId
        - jobStatus
        - jobReference
      properties:
        projectId:
          type: string
          description: ID of the project that the job belongs to
        jobId:
          type: string
          description: ID of the job
        jobType:
          type: string
          enum:
            - assessAndRepair
            - contentsQuote
            - contentsReplacement
            - glazing
            - makeSafe
            - quoteOnly
            - rectification
            - restoration
            - specialistReport
          description: Type of the job
        jobInstructions:
          type: string
          description: Instructions for completing the job
        supplierId:
          type: string
          description: ID of the supplier/vendor assigned to the job
        jobStatus:
          type: string
          enum:
            - accepted
            - awaitingA&GReview
            - closed
          description: Status of the job
        jobReference:
          type: string
          description: Reference number for the job
    ProjectDetailUpdated:
      type: object
      required:
        - projectId
      properties:
        projectId:
          type: string
          description: The ID of the project associated with the claim.
        excess:
          type: object
          required:
            - buildingExcess
            - contentsExcess
          properties:
            buildingExcess:
              type: integer
              description: The excess amount for a building claim.
            contentsExcess:
              type: integer
              description: The excess amount for a contents claim.
            fixedExcess:
              type: integer
              description: The fixed excess amount for the claim.
            totalExcess:
              type: integer
              description: The total excess amount for the claim.
          description: The excess amount for the claim.
        siteAddress:
          allOf:
            - $ref: "#/components/schemas/Address"
            - description: The site address for the claim.
        postalAddress:
          allOf:
            - description: The postal address for the claim.
            - $ref: "#/components/schemas/Address"
        insuredDetails:
          properties:
            firstName:
              type: string
              description: The first name of the insured person or company.
            lastName:
              type: string
              description: The last name of the insured person or company.
            homeNumber:
              type: string
              description: The home phone number of the insured person or company.
            mobileNumber:
              type: string
              description: The mobile phone number of the insured person or company.
            email:
              type: string
              format: email
              description: The email address of the insured person or company.
            companyName:
              type: string
              description: The name of the insured company, if applicable.
          description: The details of the insured person or company.
        eventDetails:
          type: object
          properties:
            catCode:
              type: string
              description: The cat code associated with the event
          description: The details of the event
        projectStatus:
          type: string
          enum:
            - open
            - closed
          description: The project Status
    JobDetailUpdated:
      type: object
      required:
        - jobId
      properties:
        jobId:
          type: string
          description: ID for the job
        jobStatus:
          type: string
          enum:
            - open
            - declined
            - accepted
            - cancelled
            - unassigned
            - awaitingReportAndScope
            - repairsInProgress
            - onHold
            - awaitingFinalInvoice
            - awaitingA&GReview
            - closed
          description: The status of the job.
    Address:
      type: object
      required:
        - streetNumber
        - streetName
        - suburb
        - city
        - state
        - postCode
        - country
      properties:
        unitNumber:
          type: string
          description: The unit number of the address.
        streetNumber:
          type: string
          description: The street number of the address.
        streetName:
          type: string
          description: The street name of the address.
        suburb:
          type: string
          description: The suburb of the address.
        city:
          type: string
          description: The city of the address.
        state:
          type: string
          description: The state of the address.
        postCode:
          type: string
          description: The postal code of the address.
        country:
          type: string
          description: The country of the address.
